### ISSUE TITLE
How to detect person?

### ISSUE THREAD

**Issue by IvyLiu77** [rohitkuk/Yolox_deepsort_test#1]
When I tried detect.py with an MOT sequence, it returns a video successfully, but it can only detect **traffic ligh**t rather than **person**. When I tried Tracker.py, there is an error that 
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'.

**Comment by rohitkuk** [comment]
So basically this code is in process, the reason why it would give an error is if it is not able to detect anything in the first frame or any frame. 

So in Tracker.py you have to add some try except or some conditional situation.

This is prototype code for a course actually. But you can use if for your own.

**Comment by IvyLiu77** [comment]
Thanks for your reply. Currently, I handle the problem that it cannot detect anything. But I figure out that it could merely plot the bounding boxes of the class 'traffic light'. I am not sure whether the class 'person' is detected, but anyway, no bbox is shown. I changed the parameter **filter_classes** of the **Tracker()** function (just like **Tracker(filter_classes=['person'])**), but it does not work.

**Comment by rohitkuk** [comment]
Hey No problem drop me your email address I will help getting it resolved.

**Comment by IvyLiu77** [comment]
Thank you! But I have fixed it! Thank you very much!
